application: homepage-mk2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /animated-favicon\.gif
  static_files: animated-favicon.gif
  upload: animated-favicon\.gif

- url: /css
  static_dir: css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest